#!/usr/bin/env python
from __future__ import print_function

import argparse
import urllib
import sys
import json

def main():
    parser = argparse.ArgumentParser(progname="google")
    parser.add_argument("query", help="search term")
    args = parser.parse_args()
    data = json.loads( urllib.urlopen ( 'http://ajax.googleapis.com/ajax/services/search/web?v=1.0&' + urllib.urlencode ( { 'q' : args.query } ) ).read())
    for result in data['responseData']['results']:
        title = result['titleNoFormatting']
        url = result['url']   # was URL in the original and that threw a name error exception
        print ( title + '\n' + url+ '\n')
    return 0

if __name__ == "__main__":
    sys.exit(main())
